### ISSUE TITLE
Improvise Navbar background

### ISSUE THREAD

**Issue by ayyush08** [VishnuAmit/LapProFix#19]
Hey, I just tried the app and I can see that when we enter the app first time , some  of the contents of navbar don't look properly.
Due to the black background on the top, The app logo also seems to disappear when visited for firstime

- I would like to improvise this and try implementing a glasomorphic navbar instead which is consistent throughout the app

Please assign this to me , I would like to work on this

**Comment by VishnuAmit** [comment]
Glasmorphic navbar when it is static? Because when we start scrolling, I want the navbar to be same like how it looks now. 
I changed the default theme to white and the text of navbar contents "Home, about....," looks black. But it got blended with the black background that I chose. 

So, what I did was, when we are not scrolling, ie when we open it for the first time and not scroll it, i made the text of the navbar content appear white and when we start scrolling it, it should change to its original color "black".

I hope you got it. 

But the mistake here can be visible in mobile responsive site.
where the text content of the navbar inside the dropdown box appears white till we don't scroll it.(in desktop view, it was visible due to black background, but in mobile, the dropdown box is white and the content of the text is white)

Before scrolling the page
![image](https://github.com/user-attachments/assets/76d94807-f7bd-46e2-b3bd-1f47f49174a3)


After scrolling the page.
![image](https://github.com/user-attachments/assets/36e6da4b-c0e8-488f-a49c-a26c4e39b614)


Can you fix this? 

Regarding glasmorphic, if you are trying it, maintain the navbar theme.

**Comment by ayyush08** [comment]
I believe I can fix the issue you stated, 
Regarding glasmorphic,If it works I'll make sure to maintain the theme .

So, you can assign this issue to me

**Comment by VishnuAmit** [comment]
Alright

**Comment by ayyush08** [comment]
![Screenshot 2024-10-08 200053](https://github.com/user-attachments/assets/193efa03-5b5a-42e4-9dd1-a3d75dffa0da)

I think I fixed the problem.
Check it out and let me know your feedback @VishnuAmit

**Comment by VishnuAmit** [comment]
If possible, Create a PR along with a short video of your work. I am facing issues with deployment and that is why i am asking for video instead of previewing it.

**Comment by ayyush08** [comment]
I just did PR #25 , checkout
